version: ‘3.3’
services:
  db:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb_c
    environment:
      - MONGO_INITDB_DATABASE=algotest_task
      - MONGO_INITDB_ROOT_USERNAME=${db_username}
      - MONGO_INITDB_ROOT_PASSWORD=${db_password}

    ports:
      - 27017:27017
  web:
    build: ./reactapp
    command: npm start
    container_name: reactapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./reactapp:/app
    stdin_open: true
    tty: true
    links:
      - api
  api:
    build: ./flaskapp
    hostname: api
    command: python -u app.py
    container_name: flaskapp_c
    environment:
      - "db_username=${db_username}"
      - "db_password=${db_password}"
      - "mail_id=${mail_id}"
      - "mail_password=${mail_password}"
      - "TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}"
      - "TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}"
      - "SERVICE_SID=${SERVICE_SID}"
      - "REFRESH_SECRET=${REFRESH_SECRET}"
      - "ACCESS_SECRET=${ACCESS_SECRET}"
      - "db_host=${db_host}"
    ports:
      - "5000:5000"
    volumes:
      - ./flaskapp:/app
    links:
      - db
